package com.belatrix.habilidadessociolaborales.datamodel;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import java.util.ArrayList;
import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table QUESTION.
*/
public class QuestionDao extends AbstractDao<Question, Long> {

    public static final String TABLENAME = "QUESTION";

    /**
     * Properties of entity Question.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Question = new Property(1, String.class, "question", false, "QUESTION");
        public final static Property ImageUrl = new Property(2, String.class, "imageUrl", false, "IMAGE_URL");
        public final static Property Image = new Property(3, byte[].class, "image", false, "IMAGE");
        public final static Property ValidAnswer = new Property(4, String.class, "validAnswer", false, "VALID_ANSWER");
        public final static Property InvalidAnswer1 = new Property(5, String.class, "invalidAnswer1", false, "INVALID_ANSWER1");
        public final static Property InvalidAnswer2 = new Property(6, String.class, "invalidAnswer2", false, "INVALID_ANSWER2");
        public final static Property InvalidAnswer3 = new Property(7, String.class, "invalidAnswer3", false, "INVALID_ANSWER3");
        public final static Property ScenarioId = new Property(8, Long.class, "scenarioId", false, "SCENARIO_ID");
    }

    private DaoSession daoSession;

    private Query<Question> scenario_QuestionsQuery;

    public QuestionDao(DaoConfig config) {
        super(config);
    }
    
    public QuestionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'QUESTION' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'QUESTION' TEXT," + // 1: question
                "'IMAGE_URL' TEXT," + // 2: imageUrl
                "'IMAGE' BLOB," + // 3: image
                "'VALID_ANSWER' TEXT," + // 4: validAnswer
                "'INVALID_ANSWER1' TEXT," + // 5: invalidAnswer1
                "'INVALID_ANSWER2' TEXT," + // 6: invalidAnswer2
                "'INVALID_ANSWER3' TEXT," + // 7: invalidAnswer3
                "'SCENARIO_ID' INTEGER);"); // 8: scenarioId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'QUESTION'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Question entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String question = entity.getQuestion();
        if (question != null) {
            stmt.bindString(2, question);
        }
 
        String imageUrl = entity.getImageUrl();
        if (imageUrl != null) {
            stmt.bindString(3, imageUrl);
        }
 
        byte[] image = entity.getImage();
        if (image != null) {
            stmt.bindBlob(4, image);
        }
 
        String validAnswer = entity.getValidAnswer();
        if (validAnswer != null) {
            stmt.bindString(5, validAnswer);
        }
 
        String invalidAnswer1 = entity.getInvalidAnswer1();
        if (invalidAnswer1 != null) {
            stmt.bindString(6, invalidAnswer1);
        }
 
        String invalidAnswer2 = entity.getInvalidAnswer2();
        if (invalidAnswer2 != null) {
            stmt.bindString(7, invalidAnswer2);
        }
 
        String invalidAnswer3 = entity.getInvalidAnswer3();
        if (invalidAnswer3 != null) {
            stmt.bindString(8, invalidAnswer3);
        }
 
        Long scenarioId = entity.getScenarioId();
        if (scenarioId != null) {
            stmt.bindLong(9, scenarioId);
        }
    }

    @Override
    protected void attachEntity(Question entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Question readEntity(Cursor cursor, int offset) {
        Question entity = new Question( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // question
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // imageUrl
            cursor.isNull(offset + 3) ? null : cursor.getBlob(offset + 3), // image
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // validAnswer
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // invalidAnswer1
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // invalidAnswer2
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // invalidAnswer3
            cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8) // scenarioId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Question entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setQuestion(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setImageUrl(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setImage(cursor.isNull(offset + 3) ? null : cursor.getBlob(offset + 3));
        entity.setValidAnswer(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setInvalidAnswer1(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setInvalidAnswer2(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setInvalidAnswer3(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setScenarioId(cursor.isNull(offset + 8) ? null : cursor.getLong(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Question entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Question entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "questions" to-many relationship of Scenario. */
    public List<Question> _queryScenario_Questions(Long scenarioId) {
        synchronized (this) {
            if (scenario_QuestionsQuery == null) {
                QueryBuilder<Question> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ScenarioId.eq(null));
                scenario_QuestionsQuery = queryBuilder.build();
            }
        }
        Query<Question> query = scenario_QuestionsQuery.forCurrentThread();
        query.setParameter(0, scenarioId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getScenarioDao().getAllColumns());
            builder.append(" FROM QUESTION T");
            builder.append(" LEFT JOIN SCENARIO T0 ON T.'SCENARIO_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Question loadCurrentDeep(Cursor cursor, boolean lock) {
        Question entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Scenario scenario = loadCurrentOther(daoSession.getScenarioDao(), cursor, offset);
        entity.setScenario(scenario);

        return entity;    
    }

    public Question loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Question> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Question> list = new ArrayList<Question>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Question> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Question> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
